services:
  app-collectify:
    container_name: app-collectify
    build:
      context: ./app
      dockerfile: dockerfile
    env_file:
      - .env
    volumes:
      - ./app:/app
      - /app/node_modules
    ports:
      - 5173:5173
    networks:
      - collectify
    depends_on:
      - api-collectify
  api-collectify:
    container_name: api-collectify
    build:
      context: ./api
      dockerfile: dockerfile
    volumes:
      - ./api:/usr/src/api
      - /usr/src/api/node_modules
    ports:
      - 3001:3001
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PORT=3001
    networks:
      - collectify
networks:
  collectify:
    driver: bridge
