services:
  app-partagetacollection:
    container_name: app-partagetacollection
    build:
      context: ./app
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./app:/app
      - /app/node_modules
    ports:
      - 5173:5173
    networks:
      - partagetacollection
    depends_on:
      - api-partagetacollection
  api-partagetacollection:
    container_name: api-partagetacollection
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/usr/src/api
      - /usr/src/api/node_modules
    ports:
      - 3001:3001
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PORT=3001
     
    networks:
      - partagetacollection
networks:
  partagetacollection:
    driver: bridge
