services:
  app:
    container_name: app
    build:
      context: ./app
      dockerfile: dockerFile
    env_file:
      - .env
    volumes:
      - ./app:/app
      - /app/node_modules
    ports:
      - 5173:5173
    networks:
      - collectify
    depends_on:
      - api
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: dockerFile
    volumes:
      - ./api:/usr/src/api
      - /usr/src/api/node_modules
    ports:
      - 3001:3001
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PORT=3001
    networks:
      - collectify
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:16
    volumes:
      - ./db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - collectify
  

  adminer:
    container_name: adminer
    image: adminer
    env_file:
      - .env
    ports:
      - 8080:8080
    networks:
      - collectify

networks:
  collectify:
    driver: bridge
