FROM node:20 AS builder

WORKDIR /usr/src/api

COPY package*.json ./
COPY prisma ./prisma/

# Installation des dépendances de développement
RUN npm ci
#RUN npm i pm2
RUN npm i -g nodemon

# Copie du reste des fichiers
COPY . .

# Génération du client Prisma
RUN npx prisma generate

# CMD ["pm2", "start", "server.js"]
CMD ["nodemon", "server.js"]

# docker file pour la production

