FROM node:22

WORKDIR /usr/src/api

COPY package*.json ./

RUN npm install 

COPY . .

RUN npm ci && npm i --save-dev prisma@latest && npm i @prisma/client@latest

EXPOSE 3000

RUN npx prisma generate

CMD ["npm", "run","start:dev"]