FROM node:20-alpine
WORKDIR /usr/src/api

COPY package*.json ./
COPY prisma ./prisma/

RUN npm ci --only=production

RUN npm i -g pm2

COPY . .

RUN npx prisma generate
CMD ["pm2-runtime", "ecosystem.config.js"]
